// Need to use the React-specific entry point to import `createApi`
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

interface Category {
  id: number;
  quote: string;
  author: string;
}

interface CategoriesApiResponse {
  categories: Category[];
  total: number;
  skip: number;
  limit: number;
}

// Define a service using a base URL and expected endpoints
export const categoriesApiSlice = createApi({
  baseQuery: fetchBaseQuery({ baseUrl: "https://dummyjson.com/categories" }),
  reducerPath: "categoriesApi",
  // Tag types are used for caching and invalidation.
  tagTypes: ["Categories"],
  endpoints: (build) => ({
    // Supply generics for the return type (in this case `CategoriesApiResponse`)
    // and the expected query argument. If there is no argument, use `void`
    // for the argument type instead.
    getCategories: build.query<CategoriesApiResponse, number>({
      query: (limit = 10) => `?limit=${limit}`,
      // `providesTags` determines which 'tag' is attached to the
      // cached data returned by the query.
      providesTags: (result, error, id) => [{ type: "Categories", id }],
    }),
  }),
});

// Hooks are auto-generated by RTK-Query
// Same as `categoriesApiSlice.endpoints.getCategories.useQuery`
export const { useGetCategoriesQuery } = categoriesApiSlice;
