// Need to use the React-specific entry point to import `createApi`
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

interface Transaction {
    _id?: string;
    user: string;
    status: string;
    paymentMethod: string;
    paymentStatus: string;
    transactionId: string;
    totalPrice: number;
    createdAt?: Date;
}

interface TransactionsApiResponse {
    transactions: Transaction[];
}

export interface TransactionsSliceState {
    transactions: Transaction[];
    status: "idle" | "loading" | "failed" | "fulfilled";
}

const initialState: TransactionsSliceState = {
    transactions: [],
    status: "idle",
};



// Create RTK Query API slice for transaction operations
// RTK Query provides automatic caching, background refetching, and optimistic updates
export const transactionsApiSlice = createApi({
    // Base query configuration - sets the base URL for all endpoints
    baseQuery: fetchBaseQuery({ baseUrl: "/api/user/subscription" }),
    // Unique key for this API slice in the Redux store
    reducerPath: "transactionsApi",
    // Tag types are used for caching and invalidation
    // When a mutation invalidates a tag, all queries with that tag will refetch
    tagTypes: ["Transactions"],
    // Define API endpoints (queries for fetching data, mutations for modifying data)
    endpoints: (build) => ({
        // Supply generics for the return type (in this case `TransactionsApiResponse`)
        // and the expected query argument. If there is no argument, use `void`
        // for the argument type instead.
        getTransactions: build.query<TransactionsApiResponse, void>({
            query: () => '',
            transformResponse: (response: Transaction[]) => ({ transactions: response }),
            providesTags: ['Transactions'],
        }),
        getTransaction: build.query<TransactionsApiResponse, string>({
            query: (name) => `?name=${name}`,
            providesTags: ['Transactions'],
        }),
        addTransaction: build.mutation<Transaction, any>({
            query: (newTransaction) => ({
                url: '',
                method: 'POST',
                body: newTransaction,
            }),
            invalidatesTags: [{ type: 'Transactions' }],
        }),
        deleteTransaction: build.mutation<{ deletingTransaction: Transaction }, string>({
            query: (id) => ({
                url: `/${id}`,
                method: 'DELETE',
            }),
            invalidatesTags: [{ type: 'Transactions' }],
        }),
    }),
});

// Hooks are auto-generated by RTK-Query
// Same as `transactionsApiSlice.endpoints.getTransactions.useQuery`
// Same as `transactionsApiSlice.endpoints.getTransaction.useQuery`
// Same as `transactionsApiSlice.endpoints.addTransaction.useMutation`
// Same as `transactionsApiSlice.endpoints.deleteTransaction.useMutation`
export const { useGetTransactionsQuery, useGetTransactionQuery, useAddTransactionMutation, useDeleteTransactionMutation } = transactionsApiSlice;
