// Need to use the React-specific entry point to import `createApi`
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

interface Invoice {
    _id?: string;
    invoiceNumber: string;
    invoiceDate: Date;
    description: string;
    status: boolean;
}

interface InvoicesApproveApiResponse {
    invoices: Invoice[];
}

export interface InvoicesApproveSliceState {
    invoices: Invoice[];
    status: "idle" | "loading" | "failed" | "fulfilled";
}

const initialState: InvoicesApproveSliceState = {
    invoices: [],
    status: "idle",
};



// Create RTK Query API slice for invoice operations
// RTK Query provides automatic caching, background refetching, and optimistic updates
export const invoicesApproveApiSlice = createApi({
    // Base query configuration - sets the base URL for all endpoints
    baseQuery: fetchBaseQuery({ baseUrl: "/api/user/invoice-approve" }),
    // Unique key for this API slice in the Redux store
    reducerPath: "invoicesApproveApi",
    // Tag types are used for caching and invalidation
    // When a mutation invalidates a tag, all queries with that tag will refetch
    tagTypes: ["InvoicesApprove"],
    // Define API endpoints (queries for fetching data, mutations for modifying data)
    endpoints: (build) => ({
        // Supply generics for the return type (in this case `InvoicesApiResponse`)
        // and the expected query argument. If there is no argument, use `void`
        // for the argument type instead.
        approveInvoice: build.mutation<{ invoice: Invoice; msg: string }, string>({
            query: (id) => ({
                url: `${id}`,
                method: 'PUT',
            }),
            invalidatesTags: [{ type: 'InvoicesApprove' }],
        }),
        approveAndUpdate: build.mutation<{ invoice: Invoice; msg: string }, any[]>({
            query: (invoiceDetails) => ({
                url: '',
                method: 'POST',
                body: { invoiceDetails },
            }),
            invalidatesTags: [{ type: 'InvoicesApprove' }],
        }),            
    }),
});

// Hooks are auto-generated by RTK-Query
// Same as `invoicesApiSlice.endpoints.getInvoices.useQuery`
// Same as `invoicesApiSlice.endpoints.getInvoice.useQuery`
// Same as `invoicesApiSlice.endpoints.addInvoice.useMutation`
// Same as `invoicesApiSlice.endpoints.updateInvoice.useMutation`
// Same as `invoicesApiSlice.endpoints.deleteInvoice.useMutation`
export const { useApproveInvoiceMutation, useApproveAndUpdateMutation } = invoicesApproveApiSlice;
