// Need to use the React-specific entry point to import `createApi`
import { createApi, fetchBaseQuery } from "@reduxjs/toolkit/query/react";

interface Subscription {
    _id?: string;
    user: string;
    stripeSubscriptionId: string;
    startDate?: Date;
    endDate?: Date;
    price: number;
}

interface SubscriptionsApiResponse {
    subscription: Subscription;
}

export interface SubscriptionsSliceState {
    subscriptions: Subscription[];
    status: "idle" | "loading" | "failed" | "fulfilled";
}

const initialState: SubscriptionsSliceState = {
    subscriptions: [],
    status: "idle",
};



// Create RTK Query API slice for subscription operations
// RTK Query provides automatic caching, background refetching, and optimistic updates
export const subscriptionsApiSlice = createApi({
    // Base query configuration - sets the base URL for all endpoints
    baseQuery: fetchBaseQuery({ baseUrl: "/api/user/billing" }),
    // Unique key for this API slice in the Redux store
    reducerPath: "subscriptionsApi",
    // Tag types are used for caching and invalidation
    // When a mutation invalidates a tag, all queries with that tag will refetch
    tagTypes: ["Subscriptions"],
    // Define API endpoints (queries for fetching data, mutations for modifying data)
    endpoints: (build) => ({
        // Supply generics for the return type (in this case `SubscriptionsApiResponse`)
        // and the expected query argument. If there is no argument, use `void`
        // for the argument type instead.
        getSubscriptions: build.query<SubscriptionsApiResponse, void>({
            query: () => '',
            //transformResponse: (response: Subscription) => ({ subscription: response }),
            providesTags: ['Subscriptions'],
        }),
        getSubscription: build.query<SubscriptionsApiResponse, string>({
            query: (name) => `?name=${name}`,
            providesTags: ['Subscriptions'],
        }),
        addSubscription: build.mutation<Subscription, any>({
            query: (newSubscription) => ({
                url: '',
                method: 'POST',
                body: newSubscription,
            }),
            invalidatesTags: [{ type: 'Subscriptions' }],
        }),
        deleteSubscription: build.mutation<{ deletingSubscription: Subscription }, string>({
            query: (id) => ({
                url: `/${id}`,
                method: 'DELETE',
            }),
            invalidatesTags: [{ type: 'Subscriptions' }],
        }),
    }),
});

// Hooks are auto-generated by RTK-Query
// Same as `subscriptionsApiSlice.endpoints.getSubscriptions.useQuery`
// Same as `subscriptionsApiSlice.endpoints.getSubscription.useQuery`
// Same as `subscriptionsApiSlice.endpoints.addSubscription.useMutation`
// Same as `subscriptionsApiSlice.endpoints.deleteSubscription.useMutation`
export const { useGetSubscriptionsQuery, useGetSubscriptionQuery, useAddSubscriptionMutation, useDeleteSubscriptionMutation } = subscriptionsApiSlice;
